 # enable color support of ls and also add handy aliases
 if [ -x /usr/bin/dircolors ]; then
     test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
     alias ls='ls --color=auto'
     alias dir='dir --color=auto'
     alias vdir='vdir --color=auto'
 
     alias grep='grep --color=auto'
     alias fgrep='fgrep --color=auto'
     alias egrep='egrep --color=auto'
 fi
 
# some more ls aliases
alias ll='ls -AlF'
alias la='ls -A'
alias l='ls -CF'

# Custom command aliases
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gr='git pull --rebase'
alias gl='git log'
alias c='clear'
alias update='sudo apt update && sudo apt upgrade'
alias less='less -R'

# Config file shortcuts
alias cfb='$EDITOR $HOME/.bashrc'
alias cfp='$EDITOR $HOME/.profile'
alias cfbp='$EDITOR $HOME/.profile'
alias cfn='$EDITOR $XDG_CONFIG_HOME/newsboat/urls'
alias cfba='$EDITOR $XDG_CONFIG_HOME/bash/bash_aliases'

# Git management of home directory
alias config='git --git-dir=$HOME/.home-bare-repo --work-tree=$HOME'
